### PR TITLE
Updated ER-Model

### LINKED ISSUE #84: Add E-R model
Create Entity-Relationship model and add it to the readme.

### PR DESCRIPTION
**Pull request by rishitsaiya**
Closes <a href="https://github.com/harshraj22/CSE_HUB/issues/84">Issue #84 </a>

### CODE REVIEW

**Comment by harshraj22** [comment]
Already updated :smile:

**Comment by rishitsaiya** [comment]
> Already updated 😄

That ER diagram is old isn't it?

**Comment by harshraj22** [comment]
Even the flow diagram isn't same as what was submitted :grinning:

**Comment by rishitsaiya** [comment]
> Even the flow diagram isn't same as what was submitted 😀

Cool. 😎

**Pull request closed without merging**
